data:
  window_size: 20
  prediction_days: 5
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  batch_size: 32
  rolling_window: 30
  min_periods: 5

model:
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2

training:
  lr: 0.001
  epochs: 100
  early_stopping_patience: 10
